### ISSUE TITLE
Firmware image adm_pcie_9h7_dts_dual_4x100g_dsp_8b_2022-09-22_1103.fpg fails unit tests

### ISSUE THREAD

**Issue by talonmyburgh** [realtimeradio/vla-dev#26]
All unit tests pass on all firmware images pre `adm_pcie_9h7_dts_dual_4x100g_dsp_8b_2022-09-22_1103.fpg`.
Failure message output from `python -m unittest cosmicfeng_multisource_test.py`:
```
======================================================================
FAIL: test_differentNoise_autocorr_diffSpectra (cosmicfeng_multisource_test.RunTests)
This test verifies that the autocorr block produces some different spectral results
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cosmic/dev/COSMIC-VLA-FengineVerification/cosmicfeng_multisource_test.py", line 159, in test_differentNoise_autocorr_diffSpectra
    self.assertFalse(np.sum(spectra[i] == spectra[j]) > 3,f"""Unexpected match between autocorr block {block} input {i} and input {j}""")
AssertionError: True is not false : Unexpected match between autocorr block 0 input 0 and input 2

======================================================================
FAIL: test_differentNoise_signalInfo (cosmicfeng_multisource_test.RunTests)
This test checks that signal information across all inputs differs
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cosmic/dev/COSMIC-VLA-FengineVerification/cosmicfeng_multisource_test.py", line 134, in test_differentNoise_signalInfo
    self.assertFalse(np.all(means == refmean), "Unexpected match between spectra Means")
AssertionError: True is not false : Unexpected match between spectra Means

======================================================================
FAIL: test_eqcoeffZerod_autocorr (cosmicfeng_multisource_test.RunTests)
Using an CosmicFPGAIdenticalNoise instance, we then further modify the feng to have random zero'd
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cosmic/dev/COSMIC-VLA-FengineVerification/cosmicfeng_multisource_test.py", line 260, in test_eqcoeffZerod_autocorr
    self.assertTrue(np.abs(spectra[l]) != 0.0, f"""Spectra for autocorrelation {j,j} for channel {l} is zero. Value received is {spectra[l]}.""")
AssertionError: False is not true : Spectra for autocorrelation (0, 0) for channel 256 is zero. Value received is 0j.

======================================================================
FAIL: test_identicalNoise_delay (cosmicfeng_multisource_test.RunTests)
Test phase slopes for equal noise signals with differing applied delays.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cosmic/dev/COSMIC-VLA-FengineVerification/cosmicfeng_multisource_test.py", line 221, in test_identicalNoise_delay
    self.assertFalse(max_phase_diff > (np.pi/50),
AssertionError: True is not false : Phase mismatch between inputs 0 (delay 72) and 2 (delay 67)

                Expected phase (bins [300:310]):[1.68124294 1.66590314 1.65056333 1.63522352 1.61988371 1.6045439
 1.5892041  1.57386429 1.55852448 1.54318467]
 
                Observed phase (bins [300:310]):[1.68131546 1.66628791 1.64920575 1.6353814  0.         0.
 0.         0.         1.55934763 1.54268773]

----------------------------------------------------------------------
Ran 14 tests in 11.982s

FAILED (failures=4)
```

**Comment by jack-h** [comment]
Does this now pass and if so can you remind me what the software fix was (which might point to some other firmware issue)

**Comment by talonmyburgh** [comment]
This now passes with the rearranging of the `arm_sync()` and `arm_noise()` done [here](https://github.com/COSMIC-SETI/COSMIC-VLA-FengineVerification/commit/91f6cffce73fb40ecb015130849a321ec90f6be4).

**Comment by jack-h** [comment]
Thanks. This makes absolutely no sense to me so I'll have a dig around the firmware and see if anything stands out.
Am I right in thinking that this issue could never be created with older firmware?

**Comment by jack-h** [comment]
There are two possibly relevant changes to the firmware, though I'm not sure either explain the results.
1. I think after programming the new design probably issues a rogue sync (which shouldn't matter if it is later reset with `sync.arm_sync()`
2. The new design takes a short period of time to issue a software sync (to ensure it is aligned to an allowed telescope time). But this is <10us, so should be unlikely to cause issues anywhere.

:shrug:

**Comment by talonmyburgh** [comment]
All previous versions of the firmware had no issue with the original ordering.
I had tried to `time.sleep(1)` after every `sync()` before continuing with the tests but still had failures.

**Comment by talonmyburgh** [comment]
Unit tests passed once the ordering of:
`TEST_FENG.sync.arm_sync()`
`TEST_FENG.sync.arm_noise()`
was changed to:
`TEST_FENG.sync.arm_noise()`
`TEST_FENG.sync.arm_sync()`
This change was applied [here](https://github.com/COSMIC-SETI/COSMIC-VLA-FengineVerification/commit/91f6cffce73fb40ecb015130849a321ec90f6be4).

The reasoning behind this fix is not well understood. @jack-h to review and close this issue if they see fit.

**Comment by jack-h** [comment]
I don't really believe that this alone was the fix, but since the issue has gone away I'm closing with dis-satisfaction
